### ISSUE TITLE
 No module named 'surgical_robotics_challenge.kinematics.psmFK

### ISSUE THREAD

**Issue by choucaicai** [surgical-robotics-ai/SurgicAI#1]
File "/home/jck/SurgicAI/RL/train.py", line 4, in <module>
    from Approach_env import SRC_approach
  File "/home/jck/SurgicAI/RL/Approach_env.py", line 8, in <module>
    from surgical_robotics_challenge.kinematics.psmFK import *
ModuleNotFoundError: No module named 'surgical_robotics_challenge.kinematics.psmFK'

**Comment by JinnWu686** [comment]
Thank you for your question, and apologies for the slight delay in my response. This issue is likely due to the version of the Surgical Robotic Challenge (SRC) repository you're using. The psmFK script is not included in the latest SRC version; it’s part of an older release. To resolve this, please try configuring the submodule named surgical_robotic_challenge_old in your environment.
